import { AuthKitProvider } from "@workos-inc/authkit-nextjs"
import type { Metadata } from "next"
import { headers } from "next/headers"
import Header from "../../components/layout/header"
import { getAuthorizationUrl, testAuth } from "./auth"
import Auth from "./auth/page"
import "./globals.css"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headerList = await headers()
  const pathname = headerList.get("x-current-path")
  console.log("Current path", pathname)
  const { user, isAuthenticated } = await testAuth()
  console.log("Test user", user)

  if (!isAuthenticated) {
    return <Auth />
  }

  const authKitUrl = getAuthorizationUrl(pathname || "/")

  return (
    <html
      lang="en"
      suppressHydrationWarning={process.env.NODE_ENV === "production"}
    >
      <body>
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthKitProvider>
            <main className="h-screen w-full p-2.5">
              <div className="mx-auto min-h-full max-w-5xl">
                <Header
                  isAuthenticated={isAuthenticated}
                  authKitUrl={authKitUrl}
                />
                {children}
              </div>
            </main>
          </AuthKitProvider>
        </Providers>
      </body>
    </html>
  )
}
